development: &default
  adapter: postgresql
  encoding: unicode
  database: spotify-api_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DB_USERNAME', 'spotify-api') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'spotify-api') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>

test: &test
  <<: *default
  database: spotify-api_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
