development: &development
  client_id: <%= ENV['CLIENT_ID'] %>
  client_secret: <%= ENV['CLIENT_SECRET'] %>

test:
  <<: *development
  client_id: <%= ENV['CLIENT_ID'] %>
  client_secret: <%= ENV['CLIENT_SECRET'] %>

production: &production
  client_id: <%= ENV['CLIENT_ID'] %>
  client_secret: <%= ENV['CLIENT_SECRET'] %>
